// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"
#include "Vtop.h"
#include "Vtop___024root.h"

// FUNCTIONS
Vtop__Syms::~Vtop__Syms()
{

    // Tear down scope hierarchy
    __Vhier.remove(0, &__Vscope_mkuart);
    __Vhier.remove(&__Vscope_mkuart, &__Vscope_mkuart__uart_uart_baudGen_rBaudCounter);
    __Vhier.remove(&__Vscope_mkuart, &__Vscope_mkuart__uart_uart_rRecvData);

}

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
{
        // Check resources
        Verilated::stackCheck(43);
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_mkuart.configure(this, name(), "mkuart", "mkuart", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mkuart__uart_uart_baudGen_rBaudCounter.configure(this, name(), "mkuart.uart_uart_baudGen_rBaudCounter", "uart_uart_baudGen_rBaudCounter", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_mkuart__uart_uart_rRecvData.configure(this, name(), "mkuart.uart_uart_rRecvData", "uart_uart_rRecvData", -9, VerilatedScope::SCOPE_MODULE);

    // Set up scope hierarchy
    __Vhier.add(0, &__Vscope_mkuart);
    __Vhier.add(&__Vscope_mkuart, &__Vscope_mkuart__uart_uart_baudGen_rBaudCounter);
    __Vhier.add(&__Vscope_mkuart, &__Vscope_mkuart__uart_uart_rRecvData);

    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_TOP.varInsert(__Vfinal,"CLK", &(TOP.CLK), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"EN_read_req", &(TOP.EN_read_req), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"EN_write_req", &(TOP.EN_write_req), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"RDY_read_req", &(TOP.RDY_read_req), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"RDY_write_req", &(TOP.RDY_write_req), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"RST_N", &(TOP.RST_N), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"__SYM__interrupt", &(TOP.__SYM__interrupt), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"can_take_inp", &(TOP.can_take_inp), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"io_SIN", &(TOP.io_SIN), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"io_SOUT", &(TOP.io_SOUT), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"io_SOUT_EN", &(TOP.io_SOUT_EN), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"outp_ready", &(TOP.outp_ready), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"read_req", &(TOP.read_req), false, VLVT_UINT64,VLVD_OUT|VLVF_PUB_RW,1 ,32,0);
        __Vscope_TOP.varInsert(__Vfinal,"read_req_addr", &(TOP.read_req_addr), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"read_req_size", &(TOP.read_req_size), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,1 ,1,0);
        __Vscope_TOP.varInsert(__Vfinal,"uart_ren", &(TOP.uart_ren), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"write_req", &(TOP.write_req), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"write_req_addr", &(TOP.write_req_addr), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"write_req_data", &(TOP.write_req_data), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"write_req_size", &(TOP.write_req_size), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,1 ,1,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_rl_send_dma_threshold", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_rl_send_dma_threshold), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_rl_send_rx_threshold", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_rl_send_rx_threshold), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_rl_set_charsize", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_rl_set_charsize), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_baudGen_baud_count_wire", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_baudGen_baud_count_wire), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_baud_generator_clock_enable", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_baud_generator_clock_enable), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_fifoRecv_ifc_update", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_fifoRecv_ifc_update), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_fifoXmit_ifc_update", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_fifoXmit_ifc_update), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_receive_bit_cell_time_counter", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_bit_cell_time_counter), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_receive_bit_counter", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_bit_counter), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_receive_buffer_shift", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_buffer_shift), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_receive_find_center_of_bit_cell", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_find_center_of_bit_cell), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_receive_parity_bit", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_parity_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_receive_sample_pin", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_sample_pin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_receive_stop_first_bit", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_stop_first_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_receive_stop_last_bit", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_stop_last_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_receive_wait_bit_cell_time_for_sample", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_wait_bit_cell_time_for_sample), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_receive_wait_for_start_bit", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_wait_for_start_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_rl_delay_control", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_rl_delay_control), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_rl_dma_signals", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_rl_dma_signals), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_rl_update_fifo_almost_full", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_rl_update_fifo_almost_full), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_transmit_bit_cell_time_counter", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_bit_cell_time_counter), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_transmit_bit_counter", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_bit_counter), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_transmit_buffer_load", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_buffer_load), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_transmit_buffer_shift", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_buffer_shift), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_transmit_send_parity_bit", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_send_parity_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_transmit_send_start_bit", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_send_start_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_transmit_send_stop_bit", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_send_stop_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_transmit_send_stop_bit1_5", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_send_stop_bit1_5), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_transmit_send_stop_bit2", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_send_stop_bit2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_transmit_shift_next_bit", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_shift_next_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_transmit_wait_1_bit_cell_time", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_wait_1_bit_cell_time), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_RL_uart_uart_transmit_wait_for_start_command", &(TOP.mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_wait_for_start_command), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_io_sin", &(TOP.mkuart__DOT__CAN_FIRE_io_sin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_read_req", &(TOP.mkuart__DOT__CAN_FIRE_read_req), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CAN_FIRE_write_req", &(TOP.mkuart__DOT__CAN_FIRE_write_req), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CASE_value6504_0_IF_uart_uart_fifoRecv_ifc_rDa_ETC__q1", &(TOP.mkuart__DOT__CASE_value6504_0_IF_uart_uart_fifoRecv_ifc_rDa_ETC___05Fq1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CASE_value6504_0_IF_uart_uart_fifoRecv_ifc_rDa_ETC__q2", &(TOP.mkuart__DOT__CASE_value6504_0_IF_uart_uart_fifoRecv_ifc_rDa_ETC___05Fq2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_mkuart.varInsert(__Vfinal,"CLK", &(TOP.mkuart__DOT__CLK), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"EN_read_req", &(TOP.mkuart__DOT__EN_read_req), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"EN_write_req", &(TOP.mkuart__DOT__EN_write_req), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"IF_IF_read_req_size_EQ_2_56_THEN_4_ELSE_0_CONC_ETC___d397", &(TOP.mkuart__DOT__IF_IF_read_req_size_EQ_2_56_THEN_4_ELSE_0_CONC_ETC___05F_d397), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart.varInsert(__Vfinal,"IF_read_req_addr_BITS_5_TO_0_54_EQ_0xC_65_THEN_ETC___d424", &(TOP.mkuart__DOT__IF_read_req_addr_BITS_5_TO_0_54_EQ_0xC_65_THEN_ETC___05F_d424), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"IF_uart_rg_charsize_14_EQ_7_34_THEN_uart_uart__ETC___d246", &(TOP.mkuart__DOT__IF_uart_rg_charsize_14_EQ_7_34_THEN_uart_uart___05FETC___05F_d246), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_mkuart.varInsert(__Vfinal,"IF_uart_uart_fifoRecv_ifc_rDataCount_6_ULT_0_C_ETC___d382", &(TOP.mkuart__DOT__IF_uart_uart_fifoRecv_ifc_rDataCount_6_ULT_0_C_ETC___05F_d382), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_mkuart.varInsert(__Vfinal,"IF_uart_uart_fifoRecv_ifc_rDataCount_6_ULT_0_C_ETC___d386", &(TOP.mkuart__DOT__IF_uart_uart_fifoRecv_ifc_rDataCount_6_ULT_0_C_ETC___05F_d386), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_mkuart.varInsert(__Vfinal,"IF_uart_uart_rRecvBitCount_7_EQ_uart_rg_charsi_ETC___d129", &(TOP.mkuart__DOT__IF_uart_uart_rRecvBitCount_7_EQ_uart_rg_charsi_ETC___05F_d129), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_error_status_register_write_1__SEL_1", &(TOP.mkuart__DOT__MUX_uart_uart_error_status_register_write_1___05FSEL_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_error_status_register_write_1__VAL_1", &(TOP.mkuart__DOT__MUX_uart_uart_error_status_register_write_1___05FVAL_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_error_status_register_write_1__VAL_2", &(TOP.mkuart__DOT__MUX_uart_uart_error_status_register_write_1___05FVAL_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_fifo_almost_full_write_1__VAL_2", &(TOP.mkuart__DOT__MUX_uart_uart_fifo_almost_full_write_1___05FVAL_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_out_enable_write_1__SEL_1", &(TOP.mkuart__DOT__MUX_uart_uart_out_enable_write_1___05FSEL_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_rRecvState_write_1__SEL_6", &(TOP.mkuart__DOT__MUX_uart_uart_rRecvState_write_1___05FSEL_6), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_rRecvState_write_1__VAL_1", &(TOP.mkuart__DOT__MUX_uart_uart_rRecvState_write_1___05FVAL_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_rRecvState_write_1__VAL_2", &(TOP.mkuart__DOT__MUX_uart_uart_rRecvState_write_1___05FVAL_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_rRecvState_write_1__VAL_3", &(TOP.mkuart__DOT__MUX_uart_uart_rRecvState_write_1___05FVAL_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_rRecvState_write_1__VAL_4", &(TOP.mkuart__DOT__MUX_uart_uart_rRecvState_write_1___05FVAL_4), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_rXmitDataOut_write_1__SEL_1", &(TOP.mkuart__DOT__MUX_uart_uart_rXmitDataOut_write_1___05FSEL_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_rXmitDataOut_write_1__SEL_4", &(TOP.mkuart__DOT__MUX_uart_uart_rXmitDataOut_write_1___05FSEL_4), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_rXmitDataOut_write_1__VAL_2", &(TOP.mkuart__DOT__MUX_uart_uart_rXmitDataOut_write_1___05FVAL_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_rXmitState_write_1__SEL_1", &(TOP.mkuart__DOT__MUX_uart_uart_rXmitState_write_1___05FSEL_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_rXmitState_write_1__VAL_2", &(TOP.mkuart__DOT__MUX_uart_uart_rXmitState_write_1___05FVAL_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_rXmitState_write_1__VAL_3", &(TOP.mkuart__DOT__MUX_uart_uart_rXmitState_write_1___05FVAL_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_rXmitState_write_1__VAL_4", &(TOP.mkuart__DOT__MUX_uart_uart_rXmitState_write_1___05FVAL_4), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_rXmitState_write_1__VAL_5", &(TOP.mkuart__DOT__MUX_uart_uart_rXmitState_write_1___05FVAL_5), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_rXmitState_write_1__VAL_6", &(TOP.mkuart__DOT__MUX_uart_uart_rXmitState_write_1___05FVAL_6), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_rXmitState_write_1__VAL_7", &(TOP.mkuart__DOT__MUX_uart_uart_rXmitState_write_1___05FVAL_7), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_rXmitState_write_1__VAL_8", &(TOP.mkuart__DOT__MUX_uart_uart_rXmitState_write_1___05FVAL_8), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_rg_delay_count_write_1__SEL_1", &(TOP.mkuart__DOT__MUX_uart_uart_rg_delay_count_write_1___05FSEL_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_rg_delay_count_write_1__SEL_2", &(TOP.mkuart__DOT__MUX_uart_uart_rg_delay_count_write_1___05FSEL_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"MUX_uart_uart_rg_delay_count_write_1__VAL_1", &(TOP.mkuart__DOT__MUX_uart_uart_rg_delay_count_write_1___05FVAL_1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart.varInsert(__Vfinal,"NOT_uart_uart_fifoRecv_ifc_rDataCount_6_ULT_ua_ETC___d170", &(TOP.mkuart__DOT__NOT_uart_uart_fifoRecv_ifc_rDataCount_6_ULT_ua_ETC___05F_d170), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"RDY_read_req", &(TOP.mkuart__DOT__RDY_read_req), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"RDY_write_req", &(TOP.mkuart__DOT__RDY_write_req), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"RST_N", &(TOP.mkuart__DOT__RST_N), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_rl_send_dma_threshold", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_rl_send_dma_threshold), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_rl_send_rx_threshold", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_rl_send_rx_threshold), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_rl_set_charsize", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_rl_set_charsize), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_baudGen_baud_count_wire", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_baudGen_baud_count_wire), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_baud_generator_clock_enable", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_baud_generator_clock_enable), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_fifoRecv_ifc_update", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_fifoRecv_ifc_update), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_fifoXmit_ifc_update", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_fifoXmit_ifc_update), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_receive_bit_cell_time_counter", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_bit_cell_time_counter), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_receive_bit_counter", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_bit_counter), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_receive_buffer_shift", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_buffer_shift), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_receive_find_center_of_bit_cell", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_find_center_of_bit_cell), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_receive_parity_bit", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_parity_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_receive_sample_pin", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_sample_pin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_receive_stop_first_bit", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_stop_first_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_receive_stop_last_bit", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_stop_last_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_receive_wait_bit_cell_time_for_sample", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_wait_bit_cell_time_for_sample), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_receive_wait_for_start_bit", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_wait_for_start_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_rl_delay_control", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_rl_delay_control), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_rl_dma_signals", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_rl_dma_signals), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_rl_update_fifo_almost_full", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_rl_update_fifo_almost_full), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_transmit_bit_cell_time_counter", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_bit_cell_time_counter), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_transmit_bit_counter", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_bit_counter), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_transmit_buffer_load", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_buffer_load), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_transmit_buffer_shift", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_buffer_shift), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_transmit_send_parity_bit", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_send_parity_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_transmit_send_start_bit", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_send_start_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_transmit_send_stop_bit", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_send_stop_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_transmit_send_stop_bit1_5", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_send_stop_bit1_5), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_transmit_send_stop_bit2", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_send_stop_bit2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_transmit_shift_next_bit", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_shift_next_bit), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_transmit_wait_1_bit_cell_time", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_wait_1_bit_cell_time), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_RL_uart_uart_transmit_wait_for_start_command", &(TOP.mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_wait_for_start_command), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_io_sin", &(TOP.mkuart__DOT__WILL_FIRE_io_sin), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_read_req", &(TOP.mkuart__DOT__WILL_FIRE_read_req), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"WILL_FIRE_write_req", &(TOP.mkuart__DOT__WILL_FIRE_write_req), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"_1_SL_IF_write_req_size_EQ_2_41_THEN_4_ELSE_0_C_ETC___d458", &(TOP.mkuart__DOT___1_SL_IF_write_req_size_EQ_2_41_THEN_4_ELSE_0_C_ETC___05F_d458), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"_dand2uart_uart_pwXmitCellCountReset_EN_wset", &(TOP.mkuart__DOT___dand2uart_uart_pwXmitCellCountReset_EN_wset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"_theResult___fst__h19805", &(TOP.mkuart__DOT___theResult___05F_fst___05Fh19805), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"a__h16635", &(TOP.mkuart__DOT__a___05Fh16635), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"a__h16637", &(TOP.mkuart__DOT__a___05Fh16637), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"b__h16503", &(TOP.mkuart__DOT__b___05Fh16503), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"b__h1755", &(TOP.mkuart__DOT__b___05Fh1755), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"b__h1787", &(TOP.mkuart__DOT__b___05Fh1787), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"b__h2128", &(TOP.mkuart__DOT__b___05Fh2128), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"b__h21628", &(TOP.mkuart__DOT__b___05Fh21628), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"b__h3894", &(TOP.mkuart__DOT__b___05Fh3894), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"b__h4267", &(TOP.mkuart__DOT__b___05Fh4267), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"b__h4299", &(TOP.mkuart__DOT__b___05Fh4299), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"can_take_inp", &(TOP.mkuart__DOT__can_take_inp), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"enqData__h1615", &(TOP.mkuart__DOT__enqData___05Fh1615), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"enqData__h3771", &(TOP.mkuart__DOT__enqData___05Fh3771), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"enqMask__h1616", &(TOP.mkuart__DOT__enqMask___05Fh1616), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"enqMask__h3772", &(TOP.mkuart__DOT__enqMask___05Fh3772), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"interrupt", &(TOP.mkuart__DOT__interrupt), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"io_SIN", &(TOP.mkuart__DOT__io_SIN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"io_SOUT", &(TOP.mkuart__DOT__io_SOUT), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"io_SOUT_EN", &(TOP.mkuart__DOT__io_SOUT_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"nextMask__h1610", &(TOP.mkuart__DOT__nextMask___05Fh1610), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"nextMask__h1618", &(TOP.mkuart__DOT__nextMask___05Fh1618), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"nextMask__h3766", &(TOP.mkuart__DOT__nextMask___05Fh3766), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"nextMask__h3774", &(TOP.mkuart__DOT__nextMask___05Fh3774), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"nextStorage__h1609", &(TOP.mkuart__DOT__nextStorage___05Fh1609), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"nextStorage__h1617", &(TOP.mkuart__DOT__nextStorage___05Fh1617), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"nextStorage__h3765", &(TOP.mkuart__DOT__nextStorage___05Fh3765), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"nextStorage__h3773", &(TOP.mkuart__DOT__nextStorage___05Fh3773), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"outp_ready", &(TOP.mkuart__DOT__outp_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"parity_data__h12800", &(TOP.mkuart__DOT__parity_data___05Fh12800), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_mkuart.varInsert(__Vfinal,"parity_data__h12805", &(TOP.mkuart__DOT__parity_data___05Fh12805), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_mkuart.varInsert(__Vfinal,"parity_data__h12810", &(TOP.mkuart__DOT__parity_data___05Fh12810), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_mkuart.varInsert(__Vfinal,"read_req", &(TOP.mkuart__DOT__read_req), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_mkuart.varInsert(__Vfinal,"read_req_addr", &(TOP.mkuart__DOT__read_req_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"read_req_size", &(TOP.mkuart__DOT__read_req_size), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_mkuart.varInsert(__Vfinal,"return_data__h16913", &(TOP.mkuart__DOT__return_data___05Fh16913), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"return_data__h18522", &(TOP.mkuart__DOT__return_data___05Fh18522), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"return_data__h18849", &(TOP.mkuart__DOT__return_data___05Fh18849), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"return_data__h19168", &(TOP.mkuart__DOT__return_data___05Fh19168), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"return_data__h19487", &(TOP.mkuart__DOT__return_data___05Fh19487), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_baud_value", &(TOP.mkuart__DOT__uart_baud_value), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_baud_value_D_IN", &(TOP.mkuart__DOT__uart_baud_value_D_IN), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_baud_value_EN", &(TOP.mkuart__DOT__uart_baud_value_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_ren", &(TOP.mkuart__DOT__uart_ren), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_char_decide", &(TOP.mkuart__DOT__uart_rg_char_decide), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_char_decide_D_IN", &(TOP.mkuart__DOT__uart_rg_char_decide_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_char_decide_EN", &(TOP.mkuart__DOT__uart_rg_char_decide_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_charsize", &(TOP.mkuart__DOT__uart_rg_charsize), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_charsize_D_IN", &(TOP.mkuart__DOT__uart_rg_charsize_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_charsize_EN", &(TOP.mkuart__DOT__uart_rg_charsize_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_delay_control", &(TOP.mkuart__DOT__uart_rg_delay_control), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_delay_control_D_IN", &(TOP.mkuart__DOT__uart_rg_delay_control_D_IN), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_delay_control_EN", &(TOP.mkuart__DOT__uart_rg_delay_control_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_interrupt_en", &(TOP.mkuart__DOT__uart_rg_interrupt_en), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_interrupt_en_D_IN", &(TOP.mkuart__DOT__uart_rg_interrupt_en_D_IN), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_interrupt_en_EN", &(TOP.mkuart__DOT__uart_rg_interrupt_en_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_parity", &(TOP.mkuart__DOT__uart_rg_parity), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_parity_D_IN", &(TOP.mkuart__DOT__uart_rg_parity_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_parity_EN", &(TOP.mkuart__DOT__uart_rg_parity_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_pullup_enable", &(TOP.mkuart__DOT__uart_rg_pullup_enable), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_pullup_enable_D_IN", &(TOP.mkuart__DOT__uart_rg_pullup_enable_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_pullup_enable_EN", &(TOP.mkuart__DOT__uart_rg_pullup_enable_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_rx_dma_threshold", &(TOP.mkuart__DOT__uart_rg_rx_dma_threshold), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_rx_dma_threshold_D_IN", &(TOP.mkuart__DOT__uart_rg_rx_dma_threshold_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_rx_dma_threshold_EN", &(TOP.mkuart__DOT__uart_rg_rx_dma_threshold_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_rx_threshold", &(TOP.mkuart__DOT__uart_rg_rx_threshold), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_rx_threshold_D_IN", &(TOP.mkuart__DOT__uart_rg_rx_threshold_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_rx_threshold_EN", &(TOP.mkuart__DOT__uart_rg_rx_threshold_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_stopbits", &(TOP.mkuart__DOT__uart_rg_stopbits), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_stopbits_D_IN", &(TOP.mkuart__DOT__uart_rg_stopbits_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_stopbits_EN", &(TOP.mkuart__DOT__uart_rg_stopbits_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_tx_dma_threshold", &(TOP.mkuart__DOT__uart_rg_tx_dma_threshold), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_tx_dma_threshold_D_IN", &(TOP.mkuart__DOT__uart_rg_tx_dma_threshold_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_rg_tx_dma_threshold_EN", &(TOP.mkuart__DOT__uart_rg_tx_dma_threshold_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_baudGen_rBaudCounter_ADDA", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter_ADDA), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_baudGen_rBaudCounter_ADDB", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter_ADDB), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_baudGen_rBaudCounter_DATA_A", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter_DATA_A), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_baudGen_rBaudCounter_DATA_B", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter_DATA_B), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_baudGen_rBaudCounter_DATA_C", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter_DATA_C), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_baudGen_rBaudCounter_DATA_F", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter_DATA_F), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_baudGen_rBaudCounter_Q_OUT", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter_Q_OUT), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_baudGen_rBaudCounter_SETC", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter_SETC), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_baudGen_rBaudCounter_SETF", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter_SETF), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_baudGen_rBaudCounter_value_PLUS_1_6__ETC___d78", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter_value_PLUS_1_6___05FETC___05F_d78), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_error_status_register", &(TOP.mkuart__DOT__uart_uart_error_status_register), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_error_status_register_D_IN", &(TOP.mkuart__DOT__uart_uart_error_status_register_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_error_status_register_EN", &(TOP.mkuart__DOT__uart_uart_error_status_register_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoRecv_ifc_rDataAvail", &(TOP.mkuart__DOT__uart_uart_fifoRecv_ifc_rDataAvail), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoRecv_ifc_rDataAvail_D_IN", &(TOP.mkuart__DOT__uart_uart_fifoRecv_ifc_rDataAvail_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoRecv_ifc_rDataAvail_EN", &(TOP.mkuart__DOT__uart_uart_fifoRecv_ifc_rDataAvail_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoRecv_ifc_rDataCount", &(TOP.mkuart__DOT__uart_uart_fifoRecv_ifc_rDataCount), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoRecv_ifc_rDataCount_D_IN", &(TOP.mkuart__DOT__uart_uart_fifoRecv_ifc_rDataCount_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoRecv_ifc_rDataCount_EN", &(TOP.mkuart__DOT__uart_uart_fifoRecv_ifc_rDataCount_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoRecv_ifc_rStorage", &(TOP.mkuart__DOT__uart_uart_fifoRecv_ifc_rStorage), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoRecv_ifc_rStorageMask", &(TOP.mkuart__DOT__uart_uart_fifoRecv_ifc_rStorageMask), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoRecv_ifc_rStorageMask_D_IN", &(TOP.mkuart__DOT__uart_uart_fifoRecv_ifc_rStorageMask_D_IN), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoRecv_ifc_rStorageMask_EN", &(TOP.mkuart__DOT__uart_uart_fifoRecv_ifc_rStorageMask_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoRecv_ifc_rStorage_D_IN", &(TOP.mkuart__DOT__uart_uart_fifoRecv_ifc_rStorage_D_IN), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoRecv_ifc_rStorage_EN", &(TOP.mkuart__DOT__uart_uart_fifoRecv_ifc_rStorage_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoRecv_ifc_rwDeqCount_whas", &(TOP.mkuart__DOT__uart_uart_fifoRecv_ifc_rwDeqCount_whas), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoRecv_ifc_rwEnqCount_whas", &(TOP.mkuart__DOT__uart_uart_fifoRecv_ifc_rwEnqCount_whas), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoXmit_ifc_rDataAvail", &(TOP.mkuart__DOT__uart_uart_fifoXmit_ifc_rDataAvail), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoXmit_ifc_rDataAvail_D_IN", &(TOP.mkuart__DOT__uart_uart_fifoXmit_ifc_rDataAvail_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoXmit_ifc_rDataAvail_EN", &(TOP.mkuart__DOT__uart_uart_fifoXmit_ifc_rDataAvail_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoXmit_ifc_rDataCount", &(TOP.mkuart__DOT__uart_uart_fifoXmit_ifc_rDataCount), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoXmit_ifc_rDataCount_D_IN", &(TOP.mkuart__DOT__uart_uart_fifoXmit_ifc_rDataCount_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoXmit_ifc_rDataCount_EN", &(TOP.mkuart__DOT__uart_uart_fifoXmit_ifc_rDataCount_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoXmit_ifc_rStorage", &(TOP.mkuart__DOT__uart_uart_fifoXmit_ifc_rStorage), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoXmit_ifc_rStorageMask", &(TOP.mkuart__DOT__uart_uart_fifoXmit_ifc_rStorageMask), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoXmit_ifc_rStorageMask_D_IN", &(TOP.mkuart__DOT__uart_uart_fifoXmit_ifc_rStorageMask_D_IN), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoXmit_ifc_rStorageMask_EN", &(TOP.mkuart__DOT__uart_uart_fifoXmit_ifc_rStorageMask_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoXmit_ifc_rStorage_D_IN", &(TOP.mkuart__DOT__uart_uart_fifoXmit_ifc_rStorage_D_IN), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoXmit_ifc_rStorage_EN", &(TOP.mkuart__DOT__uart_uart_fifoXmit_ifc_rStorage_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoXmit_ifc_rwDeqCount_whas", &(TOP.mkuart__DOT__uart_uart_fifoXmit_ifc_rwDeqCount_whas), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifoXmit_ifc_rwEnqCount_whas", &(TOP.mkuart__DOT__uart_uart_fifoXmit_ifc_rwEnqCount_whas), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifo_almost_full", &(TOP.mkuart__DOT__uart_uart_fifo_almost_full), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifo_almost_full_D_IN", &(TOP.mkuart__DOT__uart_uart_fifo_almost_full_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_fifo_almost_full_EN", &(TOP.mkuart__DOT__uart_uart_fifo_almost_full_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_out_enable", &(TOP.mkuart__DOT__uart_uart_out_enable), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_out_enable_D_IN", &(TOP.mkuart__DOT__uart_uart_out_enable_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_out_enable_EN", &(TOP.mkuart__DOT__uart_uart_out_enable_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_pwRecvCellCountReset_whas", &(TOP.mkuart__DOT__uart_uart_pwRecvCellCountReset_whas), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_pwRecvEnableBitCount_whas", &(TOP.mkuart__DOT__uart_uart_pwRecvEnableBitCount_whas), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_pwRecvResetBitCount_whas", &(TOP.mkuart__DOT__uart_uart_pwRecvResetBitCount_whas), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_pwXmitCellCountReset_whas", &(TOP.mkuart__DOT__uart_uart_pwXmitCellCountReset_whas), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_pwXmitEnableBitCount_whas", &(TOP.mkuart__DOT__uart_uart_pwXmitEnableBitCount_whas), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_pwXmitResetBitCount_whas", &(TOP.mkuart__DOT__uart_uart_pwXmitResetBitCount_whas), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rRecvBitCount", &(TOP.mkuart__DOT__uart_uart_rRecvBitCount), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rRecvBitCount_D_IN", &(TOP.mkuart__DOT__uart_uart_rRecvBitCount_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rRecvBitCount_EN", &(TOP.mkuart__DOT__uart_uart_rRecvBitCount_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rRecvCellCount", &(TOP.mkuart__DOT__uart_uart_rRecvCellCount), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rRecvCellCount_D_IN", &(TOP.mkuart__DOT__uart_uart_rRecvCellCount_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rRecvCellCount_EN", &(TOP.mkuart__DOT__uart_uart_rRecvCellCount_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rRecvData_dD_OUT", &(TOP.mkuart__DOT__uart_uart_rRecvData_dD_OUT), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rRecvData_sD_IN", &(TOP.mkuart__DOT__uart_uart_rRecvData_sD_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rRecvData_sEN", &(TOP.mkuart__DOT__uart_uart_rRecvData_sEN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rRecvParity", &(TOP.mkuart__DOT__uart_uart_rRecvParity), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rRecvParity_D_IN", &(TOP.mkuart__DOT__uart_uart_rRecvParity_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rRecvParity_EN", &(TOP.mkuart__DOT__uart_uart_rRecvParity_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rRecvState", &(TOP.mkuart__DOT__uart_uart_rRecvState), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rRecvState_D_IN", &(TOP.mkuart__DOT__uart_uart_rRecvState_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rRecvState_EN", &(TOP.mkuart__DOT__uart_uart_rRecvState_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rXmitBitCount", &(TOP.mkuart__DOT__uart_uart_rXmitBitCount), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rXmitBitCount_20_EQ_uart_rg_charsize_ETC___d299", &(TOP.mkuart__DOT__uart_uart_rXmitBitCount_20_EQ_uart_rg_charsize_ETC___05F_d299), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rXmitBitCount_D_IN", &(TOP.mkuart__DOT__uart_uart_rXmitBitCount_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rXmitBitCount_EN", &(TOP.mkuart__DOT__uart_uart_rXmitBitCount_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rXmitCellCount", &(TOP.mkuart__DOT__uart_uart_rXmitCellCount), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rXmitCellCount_D_IN", &(TOP.mkuart__DOT__uart_uart_rXmitCellCount_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rXmitCellCount_EN", &(TOP.mkuart__DOT__uart_uart_rXmitCellCount_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rXmitDataOut", &(TOP.mkuart__DOT__uart_uart_rXmitDataOut), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rXmitDataOut_D_IN", &(TOP.mkuart__DOT__uart_uart_rXmitDataOut_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rXmitDataOut_EN", &(TOP.mkuart__DOT__uart_uart_rXmitDataOut_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rXmitParity", &(TOP.mkuart__DOT__uart_uart_rXmitParity), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rXmitParity_D_IN", &(TOP.mkuart__DOT__uart_uart_rXmitParity_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rXmitParity_EN", &(TOP.mkuart__DOT__uart_uart_rXmitParity_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rXmitState", &(TOP.mkuart__DOT__uart_uart_rXmitState), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rXmitState_D_IN", &(TOP.mkuart__DOT__uart_uart_rXmitState_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rXmitState_EN", &(TOP.mkuart__DOT__uart_uart_rXmitState_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rg_delay_count", &(TOP.mkuart__DOT__uart_uart_rg_delay_count), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rg_delay_count_78_EQ_uart_rg_delay_c_ETC___d280", &(TOP.mkuart__DOT__uart_uart_rg_delay_count_78_EQ_uart_rg_delay_c_ETC___05F_d280), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rg_delay_count_D_IN", &(TOP.mkuart__DOT__uart_uart_rg_delay_count_D_IN), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_rg_delay_count_EN", &(TOP.mkuart__DOT__uart_uart_rg_delay_count_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_0", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_0_45_XOR_uart_uart_vrRe_ETC___d159", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_0_45_XOR_uart_uart_vrRe_ETC___05F_d159), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_0_D_IN", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_0_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_0_EN", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_0_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_1", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_1_D_IN", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_1_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_1_EN", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_1_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_2", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_2_D_IN", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_2_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_2_EN", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_2_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_3", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_3_D_IN", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_3_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_3_EN", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_3_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_4", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_4), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_4_D_IN", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_4_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_4_EN", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_4_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_5", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_5), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_5_D_IN", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_5_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_5_EN", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_5_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_6", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_6), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_6_D_IN", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_6_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_6_EN", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_6_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_7", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_7), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_7_D_IN", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_7_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrRecvBuffer_7_EN", &(TOP.mkuart__DOT__uart_uart_vrRecvBuffer_7_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_0", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_0_D_IN", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_0_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_0_EN", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_0_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_1", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_1_D_IN", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_1_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_1_EN", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_1_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_2", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_2_D_IN", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_2_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_2_EN", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_2_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_3", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_3_D_IN", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_3_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_3_EN", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_3_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_4", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_4), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_4_D_IN", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_4_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_4_EN", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_4_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_5", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_5), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_5_D_IN", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_5_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_5_EN", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_5_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_6", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_6), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_6_D_IN", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_6_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_6_EN", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_6_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_7", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_7), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_7_D_IN", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_7_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_vrXmitBuffer_7_EN", &(TOP.mkuart__DOT__uart_uart_vrXmitBuffer_7_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_wr_rx_outp_ready_wget", &(TOP.mkuart__DOT__uart_uart_wr_rx_outp_ready_wget), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"uart_uart_wr_tx_can_take_inp_wget", &(TOP.mkuart__DOT__uart_uart_wr_tx_can_take_inp_wget), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"value__h16504", &(TOP.mkuart__DOT__value___05Fh16504), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_mkuart.varInsert(__Vfinal,"value__h1874", &(TOP.mkuart__DOT__value___05Fh1874), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_mkuart.varInsert(__Vfinal,"value__h1937", &(TOP.mkuart__DOT__value___05Fh1937), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"value__h1990", &(TOP.mkuart__DOT__value___05Fh1990), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_mkuart.varInsert(__Vfinal,"value__h21629", &(TOP.mkuart__DOT__value___05Fh21629), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_mkuart.varInsert(__Vfinal,"value__h4013", &(TOP.mkuart__DOT__value___05Fh4013), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"value__h4076", &(TOP.mkuart__DOT__value___05Fh4076), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"value__h4129", &(TOP.mkuart__DOT__value___05Fh4129), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"write_req", &(TOP.mkuart__DOT__write_req), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"write_req_addr", &(TOP.mkuart__DOT__write_req_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"write_req_data", &(TOP.mkuart__DOT__write_req_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"write_req_size", &(TOP.mkuart__DOT__write_req_size), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h11088", &(TOP.mkuart__DOT__x___05Fh11088), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h11114", &(TOP.mkuart__DOT__x___05Fh11114), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h14788", &(TOP.mkuart__DOT__x___05Fh14788), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h15612", &(TOP.mkuart__DOT__x___05Fh15612), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h16334", &(TOP.mkuart__DOT__x___05Fh16334), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h16473", &(TOP.mkuart__DOT__x___05Fh16473), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h1686", &(TOP.mkuart__DOT__x___05Fh1686), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h18133", &(TOP.mkuart__DOT__x___05Fh18133), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h1837", &(TOP.mkuart__DOT__x___05Fh1837), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h1873", &(TOP.mkuart__DOT__x___05Fh1873), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h1981", &(TOP.mkuart__DOT__x___05Fh1981), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h1989", &(TOP.mkuart__DOT__x___05Fh1989), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h21595", &(TOP.mkuart__DOT__x___05Fh21595), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h21670", &(TOP.mkuart__DOT__x___05Fh21670), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h3839", &(TOP.mkuart__DOT__x___05Fh3839), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h3976", &(TOP.mkuart__DOT__x___05Fh3976), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h4012", &(TOP.mkuart__DOT__x___05Fh4012), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h4120", &(TOP.mkuart__DOT__x___05Fh4120), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h4128", &(TOP.mkuart__DOT__x___05Fh4128), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h5361", &(TOP.mkuart__DOT__x___05Fh5361), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h7065", &(TOP.mkuart__DOT__x___05Fh7065), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x__h8568", &(TOP.mkuart__DOT__x___05Fh8568), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x_error_status__h16125", &(TOP.mkuart__DOT__x_error_status___05Fh16125), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x_wget__h1480", &(TOP.mkuart__DOT__x_wget___05Fh1480), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x_wget__h3636", &(TOP.mkuart__DOT__x_wget___05Fh3636), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"x_wget__h3695", &(TOP.mkuart__DOT__x_wget___05Fh3695), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"y__h15222", &(TOP.mkuart__DOT__y___05Fh15222), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_mkuart.varInsert(__Vfinal,"y__h1687", &(TOP.mkuart__DOT__y___05Fh1687), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"y__h3840", &(TOP.mkuart__DOT__y___05Fh3840), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkuart.varInsert(__Vfinal,"y__h8232", &(TOP.mkuart__DOT__y___05Fh8232), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_mkuart.varInsert(__Vfinal,"y__h8254", &(TOP.mkuart__DOT__y___05Fh8254), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_mkuart.varInsert(__Vfinal,"y_avValue_fst__h16577", &(TOP.mkuart__DOT__y_avValue_fst___05Fh16577), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart.varInsert(__Vfinal,"z__h10207", &(TOP.mkuart__DOT__z___05Fh10207), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"z__h10214", &(TOP.mkuart__DOT__z___05Fh10214), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"z__h10221", &(TOP.mkuart__DOT__z___05Fh10221), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"z__h10228", &(TOP.mkuart__DOT__z___05Fh10228), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"z__h10235", &(TOP.mkuart__DOT__z___05Fh10235), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"z__h10242", &(TOP.mkuart__DOT__z___05Fh10242), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"z__h10249", &(TOP.mkuart__DOT__z___05Fh10249), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"z__h12725", &(TOP.mkuart__DOT__z___05Fh12725), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"z__h12732", &(TOP.mkuart__DOT__z___05Fh12732), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"z__h12739", &(TOP.mkuart__DOT__z___05Fh12739), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"z__h12746", &(TOP.mkuart__DOT__z___05Fh12746), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"z__h12753", &(TOP.mkuart__DOT__z___05Fh12753), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart.varInsert(__Vfinal,"z__h12760", &(TOP.mkuart__DOT__z___05Fh12760), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart__uart_uart_baudGen_rBaudCounter.varInsert(__Vfinal,"ADDA", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__ADDA), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart__uart_uart_baudGen_rBaudCounter.varInsert(__Vfinal,"ADDB", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__ADDB), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart__uart_uart_baudGen_rBaudCounter.varInsert(__Vfinal,"CLK", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__CLK), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart__uart_uart_baudGen_rBaudCounter.varInsert(__Vfinal,"DATA_A", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__DATA_A), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart__uart_uart_baudGen_rBaudCounter.varInsert(__Vfinal,"DATA_B", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__DATA_B), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart__uart_uart_baudGen_rBaudCounter.varInsert(__Vfinal,"DATA_C", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__DATA_C), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart__uart_uart_baudGen_rBaudCounter.varInsert(__Vfinal,"DATA_F", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__DATA_F), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart__uart_uart_baudGen_rBaudCounter.varInsert(__Vfinal,"Q_OUT", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__Q_OUT), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart__uart_uart_baudGen_rBaudCounter.varInsert(__Vfinal,"RST", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__RST), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart__uart_uart_baudGen_rBaudCounter.varInsert(__Vfinal,"SETC", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__SETC), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart__uart_uart_baudGen_rBaudCounter.varInsert(__Vfinal,"SETF", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__SETF), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart__uart_uart_baudGen_rBaudCounter.varInsert(__Vfinal,"init", const_cast<void*>(static_cast<const void*>(&(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__init))), true, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart__uart_uart_baudGen_rBaudCounter.varInsert(__Vfinal,"q_state", &(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__q_state), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_mkuart__uart_uart_baudGen_rBaudCounter.varInsert(__Vfinal,"width", const_cast<void*>(static_cast<const void*>(&(TOP.mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__width))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_mkuart__uart_uart_rRecvData.varInsert(__Vfinal,"dCLK", &(TOP.mkuart__DOT__uart_uart_rRecvData__DOT__dCLK), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart__uart_uart_rRecvData.varInsert(__Vfinal,"dD_OUT", &(TOP.mkuart__DOT__uart_uart_rRecvData__DOT__dD_OUT), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart__uart_uart_rRecvData.varInsert(__Vfinal,"dSyncReg1", &(TOP.mkuart__DOT__uart_uart_rRecvData__DOT__dSyncReg1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart__uart_uart_rRecvData.varInsert(__Vfinal,"init", const_cast<void*>(static_cast<const void*>(&(TOP.mkuart__DOT__uart_uart_rRecvData__DOT__init))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_mkuart__uart_uart_rRecvData.varInsert(__Vfinal,"sCLK", &(TOP.mkuart__DOT__uart_uart_rRecvData__DOT__sCLK), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart__uart_uart_rRecvData.varInsert(__Vfinal,"sD_IN", &(TOP.mkuart__DOT__uart_uart_rRecvData__DOT__sD_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart__uart_uart_rRecvData.varInsert(__Vfinal,"sEN", &(TOP.mkuart__DOT__uart_uart_rRecvData__DOT__sEN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart__uart_uart_rRecvData.varInsert(__Vfinal,"sRST", &(TOP.mkuart__DOT__uart_uart_rRecvData__DOT__sRST), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkuart__uart_uart_rRecvData.varInsert(__Vfinal,"sSyncReg", &(TOP.mkuart__DOT__uart_uart_rRecvData__DOT__sSyncReg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
    }
}
