// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(CLK,0,0);
        VL_IN8(RST_N,0,0);
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_0;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_find_center_of_bit_cell;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_stop_first_bit;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_stop_last_bit;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_wait_bit_cell_time_for_sample;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_wait_for_start_bit;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_send_parity_bit;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_send_start_bit;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_send_stop_bit;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_send_stop_bit1_5;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_send_stop_bit2;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_shift_next_bit;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_wait_1_bit_cell_time;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_wait_for_start_command;
        CData/*0:0*/ mkuart__DOT__MUX_uart_uart_rRecvState_write_1___05FSEL_6;
        CData/*0:0*/ mkuart__DOT__MUX_uart_uart_rXmitDataOut_write_1___05FSEL_1;
        CData/*0:0*/ mkuart__DOT__MUX_uart_uart_rXmitDataOut_write_1___05FSEL_4;
        CData/*0:0*/ mkuart__DOT__MUX_uart_uart_rXmitDataOut_write_1___05FVAL_2;
        CData/*0:0*/ mkuart__DOT__MUX_uart_uart_rXmitState_write_1___05FSEL_1;
        CData/*0:0*/ mkuart__DOT__MUX_uart_uart_rg_delay_count_write_1___05FSEL_1;
        CData/*0:0*/ mkuart__DOT__MUX_uart_uart_rg_delay_count_write_1___05FSEL_2;
        VL_IN8(read_req_size,1,0);
        VL_IN8(EN_read_req,0,0);
        VL_OUT8(RDY_read_req,0,0);
        VL_IN8(write_req_size,1,0);
        VL_IN8(EN_write_req,0,0);
        VL_OUT8(write_req,0,0);
        VL_OUT8(RDY_write_req,0,0);
        VL_IN8(io_SIN,0,0);
        VL_OUT8(io_SOUT,0,0);
        VL_OUT8(io_SOUT_EN,0,0);
        VL_OUT8(__SYM__interrupt,0,0);
        VL_OUT8(outp_ready,0,0);
        VL_OUT8(can_take_inp,0,0);
        VL_OUT8(uart_ren,0,0);
        CData/*0:0*/ mkuart__DOT__CLK;
        CData/*0:0*/ mkuart__DOT__RST_N;
        CData/*1:0*/ mkuart__DOT__read_req_size;
        CData/*0:0*/ mkuart__DOT__EN_read_req;
        CData/*0:0*/ mkuart__DOT__RDY_read_req;
        CData/*1:0*/ mkuart__DOT__write_req_size;
        CData/*0:0*/ mkuart__DOT__EN_write_req;
        CData/*0:0*/ mkuart__DOT__write_req;
        CData/*0:0*/ mkuart__DOT__RDY_write_req;
        CData/*0:0*/ mkuart__DOT__io_SIN;
        CData/*0:0*/ mkuart__DOT__io_SOUT;
        CData/*0:0*/ mkuart__DOT__io_SOUT_EN;
        CData/*0:0*/ mkuart__DOT__interrupt;
        CData/*0:0*/ mkuart__DOT__outp_ready;
        CData/*0:0*/ mkuart__DOT__can_take_inp;
        CData/*0:0*/ mkuart__DOT__uart_ren;
        CData/*0:0*/ mkuart__DOT__uart_uart_fifoRecv_ifc_rwDeqCount_whas;
        CData/*0:0*/ mkuart__DOT__uart_uart_fifoRecv_ifc_rwEnqCount_whas;
        CData/*0:0*/ mkuart__DOT__uart_uart_fifoXmit_ifc_rwDeqCount_whas;
        CData/*0:0*/ mkuart__DOT__uart_uart_fifoXmit_ifc_rwEnqCount_whas;
        CData/*0:0*/ mkuart__DOT__uart_uart_pwRecvCellCountReset_whas;
        CData/*0:0*/ mkuart__DOT__uart_uart_pwRecvEnableBitCount_whas;
        CData/*0:0*/ mkuart__DOT__uart_uart_pwRecvResetBitCount_whas;
        CData/*0:0*/ mkuart__DOT__uart_uart_pwXmitCellCountReset_whas;
        CData/*0:0*/ mkuart__DOT__uart_uart_pwXmitEnableBitCount_whas;
        CData/*0:0*/ mkuart__DOT__uart_uart_pwXmitResetBitCount_whas;
        CData/*0:0*/ mkuart__DOT__uart_uart_wr_rx_outp_ready_wget;
    };
    struct {
        CData/*0:0*/ mkuart__DOT__uart_uart_wr_tx_can_take_inp_wget;
        CData/*0:0*/ mkuart__DOT__uart_baud_value_EN;
        CData/*1:0*/ mkuart__DOT__uart_rg_char_decide;
        CData/*1:0*/ mkuart__DOT__uart_rg_char_decide_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_rg_char_decide_EN;
        CData/*5:0*/ mkuart__DOT__uart_rg_charsize;
        CData/*5:0*/ mkuart__DOT__uart_rg_charsize_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_rg_charsize_EN;
        CData/*0:0*/ mkuart__DOT__uart_rg_delay_control_EN;
        CData/*0:0*/ mkuart__DOT__uart_rg_interrupt_en_EN;
        CData/*1:0*/ mkuart__DOT__uart_rg_parity;
        CData/*1:0*/ mkuart__DOT__uart_rg_parity_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_rg_parity_EN;
        CData/*0:0*/ mkuart__DOT__uart_rg_pullup_enable;
        CData/*0:0*/ mkuart__DOT__uart_rg_pullup_enable_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_rg_pullup_enable_EN;
        CData/*2:0*/ mkuart__DOT__uart_rg_rx_dma_threshold;
        CData/*2:0*/ mkuart__DOT__uart_rg_rx_dma_threshold_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_rg_rx_dma_threshold_EN;
        CData/*4:0*/ mkuart__DOT__uart_rg_rx_threshold;
        CData/*4:0*/ mkuart__DOT__uart_rg_rx_threshold_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_rg_rx_threshold_EN;
        CData/*1:0*/ mkuart__DOT__uart_rg_stopbits;
        CData/*1:0*/ mkuart__DOT__uart_rg_stopbits_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_rg_stopbits_EN;
        CData/*2:0*/ mkuart__DOT__uart_rg_tx_dma_threshold;
        CData/*2:0*/ mkuart__DOT__uart_rg_tx_dma_threshold_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_rg_tx_dma_threshold_EN;
        CData/*3:0*/ mkuart__DOT__uart_uart_error_status_register;
        CData/*3:0*/ mkuart__DOT__uart_uart_error_status_register_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_error_status_register_EN;
        CData/*4:0*/ mkuart__DOT__uart_uart_fifoRecv_ifc_rDataAvail;
        CData/*4:0*/ mkuart__DOT__uart_uart_fifoRecv_ifc_rDataAvail_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_fifoRecv_ifc_rDataAvail_EN;
        CData/*4:0*/ mkuart__DOT__uart_uart_fifoRecv_ifc_rDataCount;
        CData/*4:0*/ mkuart__DOT__uart_uart_fifoRecv_ifc_rDataCount_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_fifoRecv_ifc_rDataCount_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_fifoRecv_ifc_rStorage_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_fifoRecv_ifc_rStorageMask_EN;
        CData/*4:0*/ mkuart__DOT__uart_uart_fifoXmit_ifc_rDataAvail;
        CData/*4:0*/ mkuart__DOT__uart_uart_fifoXmit_ifc_rDataAvail_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_fifoXmit_ifc_rDataAvail_EN;
        CData/*4:0*/ mkuart__DOT__uart_uart_fifoXmit_ifc_rDataCount;
        CData/*4:0*/ mkuart__DOT__uart_uart_fifoXmit_ifc_rDataCount_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_fifoXmit_ifc_rDataCount_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_fifoXmit_ifc_rStorage_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_fifoXmit_ifc_rStorageMask_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_fifo_almost_full;
        CData/*0:0*/ mkuart__DOT__uart_uart_fifo_almost_full_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_fifo_almost_full_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_out_enable;
        CData/*0:0*/ mkuart__DOT__uart_uart_out_enable_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_out_enable_EN;
        CData/*5:0*/ mkuart__DOT__uart_uart_rRecvBitCount;
        CData/*5:0*/ mkuart__DOT__uart_uart_rRecvBitCount_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_rRecvBitCount_EN;
        CData/*3:0*/ mkuart__DOT__uart_uart_rRecvCellCount;
        CData/*3:0*/ mkuart__DOT__uart_uart_rRecvCellCount_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_rRecvCellCount_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_rRecvParity;
        CData/*0:0*/ mkuart__DOT__uart_uart_rRecvParity_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_rRecvParity_EN;
        CData/*2:0*/ mkuart__DOT__uart_uart_rRecvState;
        CData/*2:0*/ mkuart__DOT__uart_uart_rRecvState_D_IN;
    };
    struct {
        CData/*0:0*/ mkuart__DOT__uart_uart_rRecvState_EN;
        CData/*5:0*/ mkuart__DOT__uart_uart_rXmitBitCount;
        CData/*5:0*/ mkuart__DOT__uart_uart_rXmitBitCount_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_rXmitBitCount_EN;
        CData/*3:0*/ mkuart__DOT__uart_uart_rXmitCellCount;
        CData/*3:0*/ mkuart__DOT__uart_uart_rXmitCellCount_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_rXmitCellCount_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_rXmitDataOut;
        CData/*0:0*/ mkuart__DOT__uart_uart_rXmitDataOut_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_rXmitDataOut_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_rXmitParity;
        CData/*0:0*/ mkuart__DOT__uart_uart_rXmitParity_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_rXmitParity_EN;
        CData/*3:0*/ mkuart__DOT__uart_uart_rXmitState;
        CData/*3:0*/ mkuart__DOT__uart_uart_rXmitState_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_rXmitState_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_rg_delay_count_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_0;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_0_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_0_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_1;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_1_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_1_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_2;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_2_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_2_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_3;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_3_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_3_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_4;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_4_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_4_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_5;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_5_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_5_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_6;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_6_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_6_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_7;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_7_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_7_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_0_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_0_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_1;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_1_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_1_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_2;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_2_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_2_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_3;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_3_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_3_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_4;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_4_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_4_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_5;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_5_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_5_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_6;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_6_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_6_EN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_7;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_7_D_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrXmitBuffer_7_EN;
    };
    struct {
        CData/*0:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter_ADDA;
        CData/*0:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter_ADDB;
        CData/*0:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter_SETC;
        CData/*0:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter_SETF;
        CData/*0:0*/ mkuart__DOT__uart_uart_rRecvData_dD_OUT;
        CData/*0:0*/ mkuart__DOT__uart_uart_rRecvData_sD_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_rRecvData_sEN;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_rl_send_dma_threshold;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_rl_send_rx_threshold;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_rl_set_charsize;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_baudGen_baud_count_wire;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_baud_generator_clock_enable;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_fifoRecv_ifc_update;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_fifoXmit_ifc_update;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_bit_cell_time_counter;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_bit_counter;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_buffer_shift;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_find_center_of_bit_cell;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_parity_bit;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_sample_pin;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_stop_first_bit;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_stop_last_bit;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_wait_bit_cell_time_for_sample;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_receive_wait_for_start_bit;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_rl_delay_control;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_rl_dma_signals;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_rl_update_fifo_almost_full;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_bit_cell_time_counter;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_bit_counter;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_buffer_load;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_buffer_shift;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_send_parity_bit;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_send_start_bit;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_send_stop_bit;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_send_stop_bit1_5;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_send_stop_bit2;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_shift_next_bit;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_wait_1_bit_cell_time;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_RL_uart_uart_transmit_wait_for_start_command;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_io_sin;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_read_req;
        CData/*0:0*/ mkuart__DOT__CAN_FIRE_write_req;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_rl_send_dma_threshold;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_rl_send_rx_threshold;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_rl_set_charsize;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_baudGen_baud_count_wire;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_baud_generator_clock_enable;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_fifoRecv_ifc_update;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_fifoXmit_ifc_update;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_bit_cell_time_counter;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_bit_counter;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_buffer_shift;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_parity_bit;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_receive_sample_pin;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_rl_delay_control;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_rl_dma_signals;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_rl_update_fifo_almost_full;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_bit_cell_time_counter;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_bit_counter;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_buffer_load;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_RL_uart_uart_transmit_buffer_shift;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_io_sin;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_read_req;
        CData/*0:0*/ mkuart__DOT__WILL_FIRE_write_req;
    };
    struct {
        CData/*3:0*/ mkuart__DOT__MUX_uart_uart_error_status_register_write_1___05FVAL_1;
        CData/*3:0*/ mkuart__DOT__MUX_uart_uart_error_status_register_write_1___05FVAL_2;
        CData/*3:0*/ mkuart__DOT__MUX_uart_uart_rXmitState_write_1___05FVAL_2;
        CData/*3:0*/ mkuart__DOT__MUX_uart_uart_rXmitState_write_1___05FVAL_3;
        CData/*3:0*/ mkuart__DOT__MUX_uart_uart_rXmitState_write_1___05FVAL_4;
        CData/*3:0*/ mkuart__DOT__MUX_uart_uart_rXmitState_write_1___05FVAL_5;
        CData/*3:0*/ mkuart__DOT__MUX_uart_uart_rXmitState_write_1___05FVAL_6;
        CData/*3:0*/ mkuart__DOT__MUX_uart_uart_rXmitState_write_1___05FVAL_7;
        CData/*3:0*/ mkuart__DOT__MUX_uart_uart_rXmitState_write_1___05FVAL_8;
        CData/*2:0*/ mkuart__DOT__MUX_uart_uart_rRecvState_write_1___05FVAL_1;
        CData/*2:0*/ mkuart__DOT__MUX_uart_uart_rRecvState_write_1___05FVAL_2;
        CData/*2:0*/ mkuart__DOT__MUX_uart_uart_rRecvState_write_1___05FVAL_3;
        CData/*2:0*/ mkuart__DOT__MUX_uart_uart_rRecvState_write_1___05FVAL_4;
        CData/*0:0*/ mkuart__DOT__MUX_uart_uart_error_status_register_write_1___05FSEL_1;
        CData/*0:0*/ mkuart__DOT__MUX_uart_uart_fifo_almost_full_write_1___05FVAL_2;
        CData/*0:0*/ mkuart__DOT__MUX_uart_uart_out_enable_write_1___05FSEL_1;
        CData/*7:0*/ mkuart__DOT__CASE_value6504_0_IF_uart_uart_fifoRecv_ifc_rDa_ETC___05Fq1;
        CData/*7:0*/ mkuart__DOT__CASE_value6504_0_IF_uart_uart_fifoRecv_ifc_rDa_ETC___05Fq2;
        CData/*7:0*/ mkuart__DOT__IF_uart_rg_charsize_14_EQ_7_34_THEN_uart_uart___05FETC___05F_d246;
        CData/*7:0*/ mkuart__DOT__IF_uart_uart_fifoRecv_ifc_rDataCount_6_ULT_0_C_ETC___05F_d382;
        CData/*7:0*/ mkuart__DOT__IF_uart_uart_fifoRecv_ifc_rDataCount_6_ULT_0_C_ETC___05F_d386;
        CData/*7:0*/ mkuart__DOT__parity_data___05Fh12800;
        CData/*7:0*/ mkuart__DOT__parity_data___05Fh12805;
        CData/*7:0*/ mkuart__DOT__parity_data___05Fh12810;
        CData/*7:0*/ mkuart__DOT__value___05Fh1874;
        CData/*7:0*/ mkuart__DOT__value___05Fh1990;
        CData/*7:0*/ mkuart__DOT__x___05Fh8568;
        CData/*7:0*/ mkuart__DOT__x_wget___05Fh1480;
        CData/*5:0*/ mkuart__DOT__x___05Fh11114;
        CData/*5:0*/ mkuart__DOT__x___05Fh18133;
        CData/*5:0*/ mkuart__DOT__x___05Fh7065;
        CData/*5:0*/ mkuart__DOT__y___05Fh15222;
        CData/*5:0*/ mkuart__DOT__y___05Fh8232;
        CData/*5:0*/ mkuart__DOT__y___05Fh8254;
        CData/*4:0*/ mkuart__DOT__b___05Fh16503;
        CData/*4:0*/ mkuart__DOT__b___05Fh1755;
        CData/*4:0*/ mkuart__DOT__b___05Fh1787;
        CData/*4:0*/ mkuart__DOT__b___05Fh2128;
        CData/*4:0*/ mkuart__DOT__b___05Fh21628;
        CData/*4:0*/ mkuart__DOT__b___05Fh3894;
        CData/*4:0*/ mkuart__DOT__b___05Fh4267;
        CData/*4:0*/ mkuart__DOT__b___05Fh4299;
        CData/*4:0*/ mkuart__DOT__value___05Fh1937;
        CData/*4:0*/ mkuart__DOT__value___05Fh4076;
        CData/*4:0*/ mkuart__DOT__x_error_status___05Fh16125;
        CData/*3:0*/ mkuart__DOT___1_SL_IF_write_req_size_EQ_2_41_THEN_4_ELSE_0_C_ETC___05F_d458;
        CData/*3:0*/ mkuart__DOT__x___05Fh11088;
        CData/*3:0*/ mkuart__DOT__x___05Fh5361;
        CData/*2:0*/ mkuart__DOT__IF_uart_uart_rRecvBitCount_7_EQ_uart_rg_charsi_ETC___05F_d129;
        CData/*2:0*/ mkuart__DOT__value___05Fh16504;
        CData/*2:0*/ mkuart__DOT__value___05Fh21629;
        CData/*1:0*/ mkuart__DOT__x___05Fh16473;
        CData/*1:0*/ mkuart__DOT__x___05Fh21595;
        CData/*0:0*/ mkuart__DOT__NOT_uart_uart_fifoRecv_ifc_rDataCount_6_ULT_ua_ETC___05F_d170;
        CData/*0:0*/ mkuart__DOT___dand2uart_uart_pwXmitCellCountReset_EN_wset;
        CData/*0:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter_value_PLUS_1_6___05FETC___05F_d78;
        CData/*0:0*/ mkuart__DOT__uart_uart_rXmitBitCount_20_EQ_uart_rg_charsize_ETC___05F_d299;
        CData/*0:0*/ mkuart__DOT__uart_uart_rg_delay_count_78_EQ_uart_rg_delay_c_ETC___05F_d280;
        CData/*0:0*/ mkuart__DOT__uart_uart_vrRecvBuffer_0_45_XOR_uart_uart_vrRe_ETC___05F_d159;
        CData/*0:0*/ mkuart__DOT__x___05Fh15612;
        CData/*0:0*/ mkuart__DOT__z___05Fh10207;
        CData/*0:0*/ mkuart__DOT__z___05Fh10214;
        CData/*0:0*/ mkuart__DOT__z___05Fh10221;
        CData/*0:0*/ mkuart__DOT__z___05Fh10228;
    };
    struct {
        CData/*0:0*/ mkuart__DOT__z___05Fh10235;
        CData/*0:0*/ mkuart__DOT__z___05Fh10242;
        CData/*0:0*/ mkuart__DOT__z___05Fh10249;
        CData/*0:0*/ mkuart__DOT__z___05Fh12725;
        CData/*0:0*/ mkuart__DOT__z___05Fh12732;
        CData/*0:0*/ mkuart__DOT__z___05Fh12739;
        CData/*0:0*/ mkuart__DOT__z___05Fh12746;
        CData/*0:0*/ mkuart__DOT__z___05Fh12753;
        CData/*0:0*/ mkuart__DOT__z___05Fh12760;
        CData/*0:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__CLK;
        CData/*0:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__RST;
        CData/*0:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__ADDA;
        CData/*0:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__ADDB;
        CData/*0:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__SETC;
        CData/*0:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__SETF;
        CData/*0:0*/ mkuart__DOT__uart_uart_rRecvData__DOT__sCLK;
        CData/*0:0*/ mkuart__DOT__uart_uart_rRecvData__DOT__sRST;
        CData/*0:0*/ mkuart__DOT__uart_uart_rRecvData__DOT__dCLK;
        CData/*0:0*/ mkuart__DOT__uart_uart_rRecvData__DOT__sEN;
        CData/*0:0*/ mkuart__DOT__uart_uart_rRecvData__DOT__sD_IN;
        CData/*0:0*/ mkuart__DOT__uart_uart_rRecvData__DOT__dD_OUT;
        CData/*0:0*/ mkuart__DOT__uart_uart_rRecvData__DOT__sSyncReg;
        CData/*0:0*/ mkuart__DOT__uart_uart_rRecvData__DOT__dSyncReg1;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__CLK__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__RST_N__0;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ mkuart__DOT__uart_baud_value;
        SData/*15:0*/ mkuart__DOT__uart_baud_value_D_IN;
        SData/*15:0*/ mkuart__DOT__uart_rg_delay_control;
        SData/*15:0*/ mkuart__DOT__uart_rg_delay_control_D_IN;
        SData/*15:0*/ mkuart__DOT__uart_rg_interrupt_en;
        SData/*15:0*/ mkuart__DOT__uart_rg_interrupt_en_D_IN;
        SData/*15:0*/ mkuart__DOT__uart_uart_rg_delay_count;
        SData/*15:0*/ mkuart__DOT__uart_uart_rg_delay_count_D_IN;
        SData/*15:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter_DATA_A;
        SData/*15:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter_DATA_B;
        SData/*15:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter_DATA_C;
        SData/*15:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter_DATA_F;
        SData/*15:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter_Q_OUT;
        SData/*15:0*/ mkuart__DOT__MUX_uart_uart_rg_delay_count_write_1___05FVAL_1;
        SData/*15:0*/ mkuart__DOT__IF_IF_read_req_size_EQ_2_56_THEN_4_ELSE_0_CONC_ETC___05F_d397;
        SData/*15:0*/ mkuart__DOT__x___05Fh14788;
        SData/*15:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__Q_OUT;
        SData/*15:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__DATA_A;
        SData/*15:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__DATA_B;
        SData/*15:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__DATA_C;
        SData/*15:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__DATA_F;
        SData/*15:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__q_state;
        VL_IN(read_req_addr,31,0);
        VL_IN(write_req_addr,31,0);
        VL_IN(write_req_data,31,0);
        IData/*31:0*/ mkuart__DOT__read_req_addr;
        IData/*31:0*/ mkuart__DOT__write_req_addr;
        IData/*31:0*/ mkuart__DOT__write_req_data;
        VlWide<4>/*127:0*/ mkuart__DOT__uart_uart_fifoRecv_ifc_rStorage;
        VlWide<4>/*127:0*/ mkuart__DOT__uart_uart_fifoRecv_ifc_rStorage_D_IN;
        VlWide<4>/*127:0*/ mkuart__DOT__uart_uart_fifoRecv_ifc_rStorageMask;
        VlWide<4>/*127:0*/ mkuart__DOT__uart_uart_fifoRecv_ifc_rStorageMask_D_IN;
        VlWide<4>/*127:0*/ mkuart__DOT__uart_uart_fifoXmit_ifc_rStorage;
        VlWide<4>/*127:0*/ mkuart__DOT__uart_uart_fifoXmit_ifc_rStorage_D_IN;
        VlWide<4>/*127:0*/ mkuart__DOT__uart_uart_fifoXmit_ifc_rStorageMask;
        VlWide<4>/*127:0*/ mkuart__DOT__uart_uart_fifoXmit_ifc_rStorageMask_D_IN;
    };
    struct {
        IData/*31:0*/ mkuart__DOT__IF_read_req_addr_BITS_5_TO_0_54_EQ_0xC_65_THEN_ETC___05F_d424;
        IData/*31:0*/ mkuart__DOT__x___05Fh16334;
        IData/*31:0*/ mkuart__DOT__x_wget___05Fh3636;
        VlWide<4>/*127:0*/ mkuart__DOT__enqData___05Fh1615;
        VlWide<4>/*127:0*/ mkuart__DOT__enqData___05Fh3771;
        VlWide<4>/*127:0*/ mkuart__DOT__enqMask___05Fh1616;
        VlWide<4>/*127:0*/ mkuart__DOT__enqMask___05Fh3772;
        VlWide<4>/*127:0*/ mkuart__DOT__nextMask___05Fh1610;
        VlWide<4>/*127:0*/ mkuart__DOT__nextMask___05Fh1618;
        VlWide<4>/*127:0*/ mkuart__DOT__nextMask___05Fh3766;
        VlWide<4>/*127:0*/ mkuart__DOT__nextMask___05Fh3774;
        VlWide<4>/*127:0*/ mkuart__DOT__nextStorage___05Fh1609;
        VlWide<4>/*127:0*/ mkuart__DOT__nextStorage___05Fh1617;
        VlWide<4>/*127:0*/ mkuart__DOT__nextStorage___05Fh3765;
        VlWide<4>/*127:0*/ mkuart__DOT__nextStorage___05Fh3773;
        VlWide<4>/*127:0*/ mkuart__DOT__x___05Fh1686;
        VlWide<4>/*127:0*/ mkuart__DOT__x___05Fh1873;
        VlWide<4>/*127:0*/ mkuart__DOT__x___05Fh1989;
        VlWide<4>/*127:0*/ mkuart__DOT__x___05Fh3839;
        VlWide<4>/*127:0*/ mkuart__DOT__x___05Fh4012;
        VlWide<4>/*127:0*/ mkuart__DOT__x___05Fh4128;
        VlWide<4>/*127:0*/ mkuart__DOT__y___05Fh1687;
        VlWide<4>/*127:0*/ mkuart__DOT__y___05Fh3840;
        IData/*31:0*/ mkuart__DOT___theResult___05F_fst___05Fh19805;
        IData/*31:0*/ mkuart__DOT__a___05Fh16635;
        IData/*31:0*/ mkuart__DOT__a___05Fh16637;
        IData/*31:0*/ mkuart__DOT__return_data___05Fh16913;
        IData/*31:0*/ mkuart__DOT__return_data___05Fh18522;
        IData/*31:0*/ mkuart__DOT__return_data___05Fh18849;
        IData/*31:0*/ mkuart__DOT__return_data___05Fh19168;
        IData/*31:0*/ mkuart__DOT__return_data___05Fh19487;
        IData/*31:0*/ mkuart__DOT__value___05Fh4013;
        IData/*31:0*/ mkuart__DOT__value___05Fh4129;
        IData/*31:0*/ mkuart__DOT__x___05Fh1837;
        IData/*31:0*/ mkuart__DOT__x___05Fh1981;
        IData/*31:0*/ mkuart__DOT__x___05Fh21670;
        IData/*31:0*/ mkuart__DOT__x___05Fh3976;
        IData/*31:0*/ mkuart__DOT__x___05Fh4120;
        IData/*31:0*/ mkuart__DOT__x_wget___05Fh3695;
        IData/*31:0*/ mkuart__DOT__y_avValue_fst___05Fh16577;
        IData/*31:0*/ __VactIterCount;
        VL_OUT64(read_req,32,0);
        QData/*32:0*/ mkuart__DOT__read_req;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<3> __VactTriggered;
    VlTriggerVec<3> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*0:0*/ mkuart__DOT__uart_uart_rRecvData__DOT__init = 0U;
    static constexpr SData/*15:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__init = 0U;
    static constexpr IData/*31:0*/ mkuart__DOT__uart_uart_baudGen_rBaudCounter__DOT__width = 0x00000010U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
